# Generated by Django 5.2.5 on 2025-08-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, help_text='Optional image URL for the blog', null=True),
        ),
    ]
