# Generated by Django 5.2.5 on 2025-08-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog_images/'),
        ),
    ]
